classes:
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.openstack
- system.linux.system.repo.ubuntu
#- system.linux.system.repo.glusterfs
- system.openssh.client.lab
#- system.glusterfs.client.cluster
#- system.glusterfs.client.volume.salt_pki
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.xtrabackup.server.single
#- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.physical_control_single
#- system.reclass.storage.system.openstack_gateway_cluster
- system.reclass.storage.system.openstack_gateway_single
#- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_control_single
#- system.reclass.storage.system.openstack_proxy_cluster
#- system.reclass.storage.system.openstack_database_cluster
#- system.reclass.storage.system.openstack_message_queue_cluster
#- system.reclass.storage.system.openstack_telemetry_cluster
#- system.reclass.storage.system.openstack_benchmark_single
#- cluster.mcp-on-baremetal-neutron.infra.maas
- cluster.mcp-on-baremetal-neutron.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/Mirantis/mk-lab-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$LVQkBAch$i5xD6sJZvsc2QsMNg.zQSTZGhcFQFzSqL2C6tB2g798ihePy4NHRAdTfLeN6.td12lB27RVoBM/umlggO.A.r."
    salt_master_host: ${_param:infra_config_deploy_address}
  linux:
    network:
      interface:
        ens3:
          enabled: true
          type: eth
          proto: static
          address: ${_param:deploy_address}
          netmask: ${_param:deploy_network_netmask}
          gateway: ${_param:deploy_network_gateway}
          name_servers:
            - ${_param:dns_server01}
            - ${_param:dns_server02}
        ens4: ${_param:linux_single_interface}
  salt:
    master:
      command_timeout: 600
      user:
        deploy:
          permissions: ${_param:salt_master_api_permissions}
#  maas:
#    cluster:
#      region:
#        host: ${_param:deploy_address}
#    region:
#      bind:
#        host: ${_param:deploy_address}
  reclass:
    storage:
      data_source:
        engine: local
      node:
        infra_kvm_node01:
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
#        infra_kvm_node02:
#          params:
#            keepalived_vip_priority: 101
#            linux_system_codename: xenial
#        infra_kvm_node03:
#          params:
#            keepalived_vip_priority: 102
#            linux_system_codename: xenial
        openstack_control_node01:
          params:
            linux_system_codename: xenial
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init

#        openstack_control_node02:
#          params:
#            linux_system_codename: xenial
#        openstack_control_node03:
#          params:
#            linux_system_codename: xenial
        openstack_database_node01:
          params:
            linux_system_codename: xenial
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
#        openstack_database_node02:
#          params:
#            linux_system_codename: xenial
#        openstack_database_node03:
#          params:
#            linux_system_codename: xenial
        openstack_gateway_node01:
          name: gtw01
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.gateway
          params:
            salt_master_host: 10.109.9.196
            single_address: 10.109.1.6
            tenant_address: 10.0.2.6
            deploy_address: 10.109.9.9
            linux_system_codename: xenial
        openstack_compute_rack01:
          name: ${_param:openstack_compute_rack01_hostname}<<count>>
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute.init
          repeat:
            count: 3
            start: 1
            digits: 3
            params:
              single_address:
                value: ${_param:openstack_compute_rack01_single_subnet}.<<count>>
                start: 101
              tenant_address:
                value: ${_param:openstack_compute_rack01_tenant_subnet}.<<count>>
                start: 101
              deploy_address:
                value: ${_param:openstack_compute_rack01_deploy_subnet}.<<count>>
                start: 6
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
